name: garen
description: Instalador Garen.

version: 2.0.2+2002

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations: 
    sdk: flutter

  # Google e Firebase
  google_maps_flutter: ^1.0.10
  firebase_messaging: ^7.0.3
  firebase_core: ^0.5.3
  google_fonts: ^1.1.1
  geolocator: ^6.1.13
  geocoder: ^0.2.1

  # Autenticação
  flutter_login_facebook: ^0.3.0
  firebase_auth: ^0.18.4+1
  apple_sign_in: ^0.1.0
  google_sign_in: ^4.5.9

  # Networking
  uuid: ^2.2.2
  dio: ^3.0.10
  url_launcher: ^5.7.10
  connectivity: ^2.0.2
  connectivity_wrapper: ^1.0.4

  # Hardware
  path_provider: ^1.6.24
  path: ^1.7.0
  device_info: ^1.0.0

  # Componentes
  get: ^3.24.0
  logger: ^0.9.4
  badges: ^1.1.6
  provider: ^4.1.3
  hexcolor: ^1.0.6
  carousel_pro: ^1.0.0
  supercharged: ^1.12.0
  awesome_dialog: ^1.2.1
  sqfentity_gen: ^1.4.0+2
  date_time_picker: ^1.1.0
  flutter_spinkit: "^4.1.2"
  simple_animations: ^2.4.2
  shared_preferences: ^0.5.12+4 
  mask_text_input_formatter: ^1.1.0
  currency_text_input_mask: ^0.1.0
  infinite_scroll_pagination: ^2.3.0
  flutter_inappwebview: ^4.0.0+4
  font_awesome_flutter: ^8.10.0
  argon_buttons_flutter: ^1.0.6
  permission_handler: ^5.0.1+1
  flutter_cmoon_icons: ^0.1.0
  animated_text_kit: ^2.5.4
  cupertino_icons: ^1.0.0
  image_picker: ^0.6.7+17
  flare_flutter: ^2.0.6
  brasil_fields: ^0.5.0
  cool_alert: ^1.0.3
  rxdart: ^0.25.0
  pinput: ^0.2.6
  intl: ^0.16.1

dev_dependencies:
  build_runner: ^1.10.4
  build_verify: ^1.1.1
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/images/splash.png"
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
   - assets/images/flags/
   - assets/images/
   - assets/flrs/
   - assets/gifs/
   - assets/data/
   - assets/locale/
  
fonts:
   - family: Garen
     fonts:
       - asset: assets/fonts/AlexBrush-Regular.ttf